export const COUNTRIES = [
    { value: 'albania', viewValue: 'Albania' },
    { value: 'andorra', viewValue: 'Andorra' },
    { value: 'austria', viewValue: 'Austria' },
    { value: 'belarus', viewValue: 'Belarus' },
    { value: 'belgium', viewValue: 'Belgium' },
    { value: 'bosniaandherzegovina', viewValue: 'Bosnia and Herzegovina' },
    { value: 'bulgaria', viewValue: 'Bulgaria' },
    { value: 'croatia', viewValue: 'Croatia' },
    { value: 'cyprus', viewValue: 'Cyprus' },
    { value: 'czechrepublic', viewValue: 'Czech Republic' },
    { value: 'denmark', viewValue: 'Denmark' },
    { value: 'estonia', viewValue: 'Estonia' },
    { value: 'finland', viewValue: 'Finland' },
    { value: 'france', viewValue: 'France' },
    { value: 'georgia', viewValue: 'Georgia' },
    { value: 'germany', viewValue: 'Germany' },
    { value: 'greece', viewValue: 'Greece' },
    { value: 'hungary', viewValue: 'Hungary' },
    { value: 'iceland', viewValue: 'Iceland' },
    { value: 'ireland', viewValue: 'Ireland' },
    { value: 'italy', viewValue: 'Italy' },
    { value: 'kosovo', viewValue: 'Kosovo' },
    { value: 'latvia', viewValue: 'Latvia' },
    { value: 'liechtenstein', viewValue: 'Liechtenstein' },
    { value: 'lithuania', viewValue: 'Lithuania' },
    { value: 'luxembourg', viewValue: 'Luxembourg' },
    { value: 'malta', viewValue: 'Malta' },
    { value: 'moldova', viewValue: 'Moldova' },
    { value: 'monaco', viewValue: 'Monaco' },
    { value: 'montenegro', viewValue: 'Montenegro' },
    { value: 'netherlands', viewValue: 'Netherlands' },
    { value: 'northmacedonia', viewValue: 'North Macedonia' },
    { value: 'norway', viewValue: 'Norway' },
    { value: 'poland', viewValue: 'Poland' },
    { value: 'portugal', viewValue: 'Portugal' },
    { value: 'romania', viewValue: 'Romania' },
    { value: 'russia', viewValue: 'Russia' },
    { value: 'sanmarino', viewValue: 'San Marino' },
    { value: 'serbia', viewValue: 'Serbia' },
    { value: 'slovakia', viewValue: 'Slovakia' },
    { value: 'slovenia', viewValue: 'Slovenia' },
    { value: 'spain', viewValue: 'Spain' },
    { value: 'sweden', viewValue: 'Sweden' },
    { value: 'switzerland', viewValue: 'Switzerland' },
    { value: 'ukraine', viewValue: 'Ukraine' },
    { value: 'unitedkingdom', viewValue: 'United Kingdom' },
];
